import type { TmdbMovieDetailsDto } from '../types/TmdbMovieDetailsDto'
import type { MovieDetails } from '~~/shared/types/media'

export function mapTmdbMovieDetails(movie: TmdbMovieDetailsDto): MovieDetails {
  return {
    adult: movie.adult,
    backdropPath: movie.backdrop_path,
    belongsToCollection: movie.belongs_to_collection
      ? {
          id: movie.belongs_to_collection.id,
          name: movie.belongs_to_collection.name,
          posterPath: movie.belongs_to_collection.poster_path,
          backdropPath: movie.belongs_to_collection.backdrop_path,
        }
      : null,
    budget: movie.budget,
    genres: movie.genres,
    homepage: movie.homepage,
    id: movie.id,
    imdbId: movie.imdb_id,
    originCountry: movie.origin_country,
    originalLanguage: movie.original_language,
    originalTitle: movie.original_title,
    overview: movie.overview,
    popularity: movie.popularity,
    posterPath: movie.poster_path,
    productionCompanies: movie.production_companies.map(company => ({
      id: company.id,
      logoPath: company.logo_path,
      name: company.name,
      originCountry: company.origin_country,
    })),
    productionCountries: movie.production_countries.map(country => ({
      iso31661: country.iso_3166_1,
      name: country.name,
    })),
    releaseDate: movie.release_date,
    revenue: movie.revenue,
    runtime: movie.runtime,
    spokenLanguages: movie.spoken_languages.map(language => ({
      englishName: language.english_name,
      iso6391: language.iso_639_1,
      name: language.name,
    })),
    status: movie.status,
    tagline: movie.tagline,
    title: movie.title,
    video: movie.video,
    voteAverage: movie.vote_average,
    voteCount: movie.vote_count,
    credits: {
      cast: movie.credits.cast.map(item => ({
        adult: item.adult,
        castId: item.cast_id,
        character: item.character,
        creditId: item.credit_id,
        gender: item.gender,
        id: item.id,
        knownForDepartment: item.known_for_department,
        name: item.name,
        order: item.order,
        originalName: item.original_name,
        popularity: item.popularity,
        profilePath: item.profile_path,
      })),
      crew: movie.credits.crew.map(item => ({
        adult: item.adult,
        creditId: item.credit_id,
        department: item.department,
        gender: item.gender,
        id: item.id,
        job: item.job,
        knownForDepartment: item.known_for_department,
        name: item.name,
        originalName: item.original_name,
        popularity: item.popularity,
        profilePath: item.profile_path,
      })),
    },
    similar: {
      page: movie.similar.page,
      results: movie.similar.results.map(similar => ({
        adult: similar.adult,
        backdropPath: similar.backdrop_path,
        genreIds: similar.genre_ids,
        id: similar.id,
        title: similar.title,
        originalLanguage: similar.original_language,
        originalTitle: similar.original_title,
        overview: similar.overview,
        popularity: similar.popularity,
        posterPath: similar.poster_path,
        releaseDate: similar.release_date,
        video: similar.video,
        voteAverage: similar.vote_average,
        voteCount: similar.vote_count,
      })),
      totalPages: movie.similar.total_pages,
      totalResults: movie.similar.total_results,
    },
    videos: {
      results: movie.videos.results.map(video => ({
        id: video.id,
        iso31661: video.iso_3166_1,
        iso6391: video.iso_639_1,
        key: video.key,
        name: video.name,
        official: video.official,
        publishedAt: video.published_at,
        site: video.site,
        size: video.size,
        type: video.type,
      })),
    },
  }
}
